-include("ecapnp_records.hrl").

-type element_size() :: ecapnp:element_size().
-type field_name() :: ecapnp:field_name().
-type field_type() :: ecapnp:field_type().
-type field_value() :: ecapnp:field_value().
-type message() :: ecapnp:message().
-type node_type() :: ecapnp:node_type().
-type node_types() :: ecapnp:node_types().
-type object() :: ecapnp:object().
-type object_field() :: ecapnp:object_field().
-type object_fields() :: ecapnp:object_fields().
-type ref_kind() :: ecapnp:ref_kind().
-type schema() :: ecapnp:schema().
-type schema_node() :: ecapnp:schema_node().
-type schema_type() :: ecapnp:schema_type().
-type segment_id() :: ecapnp:segment_id().
-type type_id() :: ecapnp:type_id().
-type type_name() :: ecapnp:type_name().
-type value() :: ecapnp:value().
